# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_all_ORFs_as_List <- function(fastaSeqs, startCodon, stopCodon, longestORF, minimumLength) {
    .Call('_ORFik_get_all_ORFs_as_List', PACKAGE = 'ORFik', fastaSeqs, startCodon, stopCodon, longestORF, minimumLength)
}

get_all_orfs_as_matrix <- function(main_string, s, e, longestORF, minimumLength) {
    .Call('_ORFik_get_all_orfs_as_matrix', PACKAGE = 'ORFik', main_string, s, e, longestORF, minimumLength)
}

get_all_orfs_as_IRanges <- function(main_string, s, e, longestORF, minimumLength) {
    .Call('_ORFik_get_all_orfs_as_IRanges', PACKAGE = 'ORFik', main_string, s, e, longestORF, minimumLength)
}

map_to_GRangesC <- function(ORFdef, grangesObj, grangesObjStrings, transcriptName) {
    .Call('_ORFik_map_to_GRangesC', PACKAGE = 'ORFik', ORFdef, grangesObj, grangesObjStrings, transcriptName)
}

